version: '3.8'

services:
  # Parental Controls Application
  parental-controls:
    build: .
    container_name: parental-controls-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ~/.ssh:/home/node/.ssh:ro  # SSH keys for OPNSense access
    networks:
      - parental-controls-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=false"  # Disable Traefik if using it
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: parental-controls-nginx
    restart: unless-stopped
    ports:
      - "8443:80"  # Map port 8443 on host to port 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - parental-controls
    networks:
      - parental-controls-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

networks:
  parental-controls-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  config:
    driver: local
  logs:
    driver: local
